--TODO: REWRITE THIS ENTIRE FILE
term.setBackgroundColor(colors.black)
term.setTextColor(colors.white)
term.clear()
term.setCursorPos(1,1)
print("Welcome to AIOS X26 CARBON")
print("PLEASE NOTE THAT THIS IS A EARLY ALPHA BUILD")
print("")
print("This script will get everything installed and setup for you!")
sleep(3)
function fetch(file,path)
    shell.run("wget","https://raw.githubusercontent.com/TheAio/cc-aios-x26/refs/heads/main/"..file,path)
end
fetch("ver","/.sys/common/.ver")
fetch("main/10.prgm","/.boot/init/10.prgm")
fetch("main/COPYRIGHT.readme","/.sys/common/agreements/COPYRIGHT.readme")
fetch("main/MORAL.readme","/.sys/common/agreements/MORAL.readme")
fetch("main/main.lua","/.sys/main.lua")
fetch("main/OOTB.lua","/.sys/common/OOTB.lua")
fetch("main/update.lua","/.sys/common/update.lua")
fetch("main/boot.lua","boot.lua")
fetch("main/boot.wp","boot.wp")
h=fs.open("startup.lua","w")
h.writeLine("shell.run('boot')")
h.writeLine("os.reboot()")
h.close()
os.reboot()
